[tool.poetry]
name = "slide"
version = "0.1.0"
description = "Smart Line Identification and Data Extraction"
authors = ["Garcez, Vitor Hugo <vitor_hgbds@hotmail.com>"]
readme = "README.md"
license = "GNU GENERAL PUBLIC LICENSE"

[tool.poetry.dependencies]
python = ">=3.11"
dlisio = ">=1.0.3,<2.0.0"
rich = "^13.9.4"
bs4 = "^0.0.2"
matplotlib = "^3.10.0"
lxml = "^5.3.0"
tqdm = "^4.67.1"
aiohttp = "^3.11.12"
aria2p = {extras = ["tui"], version = "^0.12.1"}
ipykernel = "^6.30.1"
pandas = "^2.3.2"
pydantic = "^2.11.7"
seaborn = "^0.13.2"
plotly = "^6.3.1"
nbformat = "^5.10.4"
scipy = "^1.16.2"
scikit-learn = "^1.7.2"
mlflow = "^3.5.1"

[tool.poetry.group.dev.dependencies]
pre-commit = ">=4.1.0,<5.0.0"
ruff = ">=0.9.4,<0.10.0"
mypy = ">=1.14.1,<2.0.0"
ipykernel = "^6.29.5"

[tool.ruff]
exclude = [".git", ".mypy_cache", ".ruff_cache", "venv", "./gas/models/deprecated/"]
line-length = 120
indent-width = 4
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true

[tool.mypy]
mypy_path = "slide"
follow_imports = "silent"
no_implicit_optional = true
warn_unused_ignores = true
show_error_codes = true
disable_error_code = "func-returns-value"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
slide = 'slide.cli:cli'
