model_type: 'KNN'
params:
  n_neighbors:
    low: 3
    high: 15
    step: 2
  weights:
    - 'uniform'
    - 'distance'
  p:
    - 1
    - 2
  algorithm:
    - 'auto'
    - 'ball_tree'
    - 'kd_tree'