policy:
  total_wells: 400
  apply_scaling: true
  apply_presence: true
  apply_rolling_stats: true
  rolling_window: 5
  labels:
    - 'ARENITO'
    - 'FOLHELHO'
    - 'SILTITO'
    - 'CALCILUTITO'
    - 'CALCARENITO'
    - 'ARGILITO'
    - 'CALCARIO'
    - 'CONGLOMERADO'
    - 'DIABASIO'
    - 'ANIDRITA'
    - 'AREIA'
    - 'DIAMICTITO'
    - 'MARGA'
    - 'ARGILA'
    - 'DOLOMITO'
  test_size: 0.2
  random_state: 42