model_type: 'BILSTM'
params:
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  batch_size: 1024
  learning_rate: 0.0001
  num_workers: 2
policy:
  name: 'clean-1665-wells'
  total_wells: 1665
  apply_scaling: true
  apply_presence: false
  apply_rolling_stats: false
  labels:
    - 'ARENITO'
    - 'FOLHELHO'
    - 'SILTITO'
    - 'CALCILUTITO'
    - 'CALCARENITO'
    - 'ARGILITO'
    - 'CALCARIO'
    - 'CONGLOMERADO'
    - 'DIABASIO'
    - 'ANIDRITA'
    - 'AREIA'
    - 'DIAMICTITO'
    - 'MARGA'
    - 'ARGILA'
    - 'DOLOMITO'
  test_size: 0.2
  random_state: 42
trials: 1